// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'

// lang.js
export const SET_LOCALE = 'SET_LOCALE'

// music.js
export const SET_ACTIVE_TRACK = 'SET_ACTIVE_TRACK'
export const FETCH_MUSIC = 'FETCH_MUSIC'
export const SET_MUSIC_LIST = 'SET_MUSIC_LIST'
export const SET_USER_PLAY_LISTS = 'SET_USER_PLAY_LISTS'
export const FETCH_USER_PLAY_LISTS = 'FETCH_USER_PLAY_LISTS'
export const SET_CURRENT_PLAYLIST = 'SET_CURRENT_PLAYLIST'
